-- Enable uuid-ossp extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create monitoring_sessions table
CREATE TABLE IF NOT EXISTS monitoring_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    status TEXT NOT NULL CHECK (status IN ('active', 'stopped', 'completed')),
    config JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create alerts table
CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES monitoring_sessions(id),
    violation_type TEXT NOT NULL,
    image_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE monitoring_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public access (since we're using anon key for now)
-- In production, you'd restrict this to authenticated users or specific roles
CREATE POLICY "Allow public select on monitoring_sessions" ON monitoring_sessions FOR SELECT USING (true);
CREATE POLICY "Allow public insert on monitoring_sessions" ON monitoring_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on monitoring_sessions" ON monitoring_sessions FOR UPDATE USING (true);

CREATE POLICY "Allow public select on alerts" ON alerts FOR SELECT USING (true);
CREATE POLICY "Allow public insert on alerts" ON alerts FOR INSERT WITH CHECK (true);

-- Create storage bucket for violation snapshots
INSERT INTO storage.buckets (id, name, public)
VALUES ('violation-snapshots', 'violation-snapshots', true)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS on storage objects (usually enabled by default, but good to be explicit)
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- Create storage policies for the violation-snapshots bucket
-- Allow uploads (INSERT) for anon/authenticated users
CREATE POLICY "Allow Uploads"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'violation-snapshots' );

-- Allow viewing (SELECT) for anon/authenticated users
CREATE POLICY "Allow Public View"
ON storage.objects FOR SELECT
USING ( bucket_id = 'violation-snapshots' );

